# Generated by Django 2.2.4 on 2019-08-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mehedi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mob', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('price_ohos', models.IntegerField()),
                ('price_ohbs', models.IntegerField()),
                ('price_thos', models.IntegerField()),
                ('price_thbs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mehedi_Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mob', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('hand', models.CharField(max_length=50)),
                ('no_of_artist', models.IntegerField()),
            ],
        ),
    ]
