# Generated by Django 2.2.4 on 2019-08-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mob', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('event_type', models.CharField(max_length=50)),
                ('number_of_photographer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mob', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('photographer_type', models.CharField(max_length=20)),
                ('small_event_charge', models.IntegerField()),
                ('large_event_charge', models.IntegerField()),
            ],
        ),
    ]
