# Generated by Django 2.2.4 on 2019-08-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mob', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('event_type', models.CharField(max_length=20)),
                ('volunteer_number', models.CharField(max_length=20)),
                ('hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mob', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
