# Generated by Django 2.2.4 on 2019-08-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver_Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mob', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=500)),
                ('transmission', models.CharField(max_length=20)),
                ('hours', models.IntegerField()),
            ],
        ),
    ]
